name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CXX: g++-4.8

jobs:
  build:
    name: Build assets
    runs-on: [ubuntu-latest]
    steps:

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Get yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.github/workflows/**.yml') }}


      - name: Install Node.js dependencies
        run: yarn

      - name: Build assets
        run: yarn build

      - name: Test
        run: |
          yarn test
          yarn lint:eslint
          yarn lint:prettier
